### ISSUE TITLE
Validate app engine project IDs

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#104]
In new app engine wizard, show some sort of error when user has typed an illegal App Engine Project ID such as one that contains spaces. 

First, figure out if App Engine has documented this anywhere. A quick google search doesn't find it so I'm not sure what is and is not illegal.

**Comment by briandealwis** [comment]
From the Developers Console when using a period
```
Project name has invalid characters. Enter letters, numbers, quotes, hyphens, spaces or exclamation points.
```
