### ISSUE TITLE
set up target platforms for Mars and Neon

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#13]
as Brian did for the legacy plugin in https://github.com/GoogleCloudPlatform/google-plugin-for-eclipse/commit/79dae2c02a027fa6b2e7f9a530af84ed8f010993

**Comment by elharo** [comment]
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
elharo@elharo:/tmp$ cd gcloud-eclipse-tools
elharo@elharo:/tmp/gcloud-eclipse-tools$ mvn clean install
[INFO] Scanning for projects...
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.

**Comment by briandealwis** [comment]
I'm happy to take this if you'd prefer @elharo

**Comment by elharo** [comment]
Let's figure out what we want to do about .tpd/.target befroe we proceed here.
