### ISSUE TITLE
Don't put project ID in appengine-web.xml

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#133]
Verify this against public App Engine docs, but apparently this is now supposed to be provided at deploy time.

**Comment by elharo** [comment]
Per https://cloud.google.com/appengine/docs/java/config/appref the application element with the project ID is required.

**Comment by elharo** [comment]
OTOH the published XSD scheam does not require this element:

<xs:element type="xs:string" name="application" minOccurs="0"/>

**Comment by briandealwis** [comment]
Interesting there's no `maxOccurs`.  Perhaps there's a safeguard to verify that the deployed-to project must match one of the `application`s, if provided.

**Comment by elharo** [comment]
The latest maven archetypes do not put an application element in pom.xml but do create something like this:

    <properties>
        <app.id>your-app-id</app.id>
        <app.version>1</app.version>
        <appengine.version>1.9.37</appengine.version>
        <gcloud.plugin.version>2.0.9.74.v20150814</gcloud.plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>
    </properties>

**Comment by elharo** [comment]
OK, this is very weird. As soon as the pom.xml is created Eclipse seems to rewrite it into a much more complex form that remove the application element and adds properties/app.id

I guess this is something to do with facets, but it's not at all clear to me how this is happening.

**Comment by elharo** [comment]
So after much mucking with maven the result is

[INFO] Retrieving Google App Engine Java SDK from Maven
[INFO] Updating Google App Engine Application
[INFO] Running -V 3 --oauth2 update /Users/elharo/runtime-EclipseApplication/basic/target/HelloAppEngine-1.0-SNAPSHOT
Reading application configuration data...
Bad configuration: No app id supplied and XML files have no <application> element

I.e. it seems that the application element is indeed required in the appengine-web.xml, at least with he currently shipped toolchain.
