### ISSUE TITLE
Configure Generated Project to build in Eclipse

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#134]
1. Attach Java nature
2. Set src/main/java in classpath entries
3. Attach servlet jar

Or can we just do this all with facets?

**Comment by elharo** [comment]
ISimpleWebFacetInstallDataModelProperties.CONTENT_DIR, new Path("src/main/webapp")

except that doesn't seem to be quite right.
search for WebContent in WST to find relevant code

**Comment by elharo** [comment]
see also SimpleWebFacetInstallDelegate

**Comment by elharo** [comment]
SimpleWebFacetInstallDelegate.execute uses the config to set up a lot of the project

**Comment by elharo** [comment]
Tentative next step: add cloudSdkDirectory to wizard and add to classpath:

${cloudSdkDirectory}/platform/google_appengine/google/appengine/tools/java/lib/shared/servlet-api.jar"
${cloudSdkDirectory}/platform/google_appengine/google/appengine/tools/java/lib/shared/jsp-api.ja

Probably first figure out how to add to classpath a hard coded path

**Comment by briandealwis** [comment]
There's two parts to this:

1. This is where the `IRuntime`'s come into to play.  These are normally added via an `IRuntimeComponent` associated with the `IRuntime`.  Some of these provide an adapter to `IClasspathProvider` that pulls them from the `IRuntime`.

2. Where does the runtime pull these jars from?  Patrick recommended against using `gcloud` as the canonical place to locate them.  But that could be a later step.

**Comment by elharo** [comment]
I can confirm that when I manually add the Generic Server Framework Runtime to the project that the classpath is configured appropriately; i.e. servlet-api.jar and the other jar are added and it all builds. 

This might be a stopgap until the new runtime is ready. If nothing else, I can figure out how to attach a runtime programmatically when creating a project.

**Comment by elharo** [comment]
FYI org.eclipse.wst.project.facet.ProductManager contains many of the keys we may need to set.

**Comment by elharo** [comment]
FYI IFacetedProject.setTargetedRuntimes/setPrimaryRuntime is how we attach a runtime to a project. Now I need to figure out how to create/point to a runtime. The Dynmaic Web Project wizard provides UI for this. Do we need that?

**Comment by elharo** [comment]
This is probably not quite right but something like this should be in the direction of what we need:

      Set<IRuntime> runtimes = RuntimeManager.getRuntimes();
      IRuntime appEngineRuntime = RuntimeManager.getRuntime("App Engine");
      facetedProject.setTargetedRuntimes(runtimes, monitor);
      facetedProject.setPrimaryRuntime(appEngineRuntime, monitor);
