### ISSUE TITLE
Set user agent string for gcloud

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#137]
for analytics tracking:

1. Figure out what user agent string we want (e.g. gcloud-eclipse)
2. Set the environment variable "CLOUDSDK_METRICS_ENVIRONMENT" to "gcloud-eclipse" or whatever) when invoking gcloud

see https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/master/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineAction.java#L89

**Comment by chanseokoh** [comment]
Please make sure this works on Mac and Windows too.
