### ISSUE TITLE
Get user consent for analytics on install

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#138]
Need to explicitly ask user to consent to usage tracking via GA when plugin is installed (or updated if from a pre-analytics version)

**Comment by chanseokoh** [comment]
@briandealwis I am working on displaying a opt-in dialog (pop-up, notification, or whatever) that asks for a user consent on collecting usage metrics. I first tried `org.eclipse.jface.dialogs.PopupDialog`, but this pop-up is way too transient in that it disappears as soon as a user clicks on anywhere else. I am now trying to extend `org.eclipse.jface.dialogs.Dialog` directly to have a custom dialog, but I wonder if there is a better option. Ideally, it should be a small dialog having non-modal, less-intrusive, and notification-like characteristics.

**Comment by briandealwis** [comment]
Hmm, I thought there was a way to prevent the transient-ness of the `InputDialog`, but nothing pops up (hohoho).  Given the importance of the user's decision, wouldn't it be best to use a normal modal dialog?

**Comment by chanseokoh** [comment]
@briandealwis Now, we should decide when and how to show the Analytics opt-in dialog. (It's a matter of calling [a method](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/blob/master/plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java#L179), which can be called many times.)

@rdayal suggested to do so at the "activation" time of our plugin (doing lazily and in the right context) and ask for advice from you. Should the method call be in `Activator.start()` in each bundle that has an `Activator`? Will this work okay technically? Any opinions/suggestions/concerns?

**Comment by chanseokoh** [comment]
@briandealwis Any ideas about https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/138#issuecomment-227902048?

**Comment by briandealwis** [comment]
Sorry @chanseokoh I missed the above in the noise of Github notifications.  I think we need to both do it from the activator, which should ideally coincide with the first trigger of a Cloud Tools action.  But bundles may be activated in states where we can't prompt the user (below), so we also need to be able to prompt from within the ping code have an unknown user-confirmation state.

We still need to be able to prompt independent of the activator.  We can't just rely on the activator as a bundle may be activated before the SWT `Display` has been created by the Eclipse Workbench.  We must ensure that the activator never creates a `Display` instance as it's not appropriate to create a display from any thread but the main thread (so never use `Display.getDefault()`) — a bundle may be activated on any thread.

**Comment by chanseokoh** [comment]
I did some testing and relying on Activator.starts() doesn't really work well. The sdk.internal Activator is triggered when the Eclipse is being launched. The localserver Activator is triggered later when it is somehow used (e.g., when opening a preference dialog), but `PlatformUI.getWorkbench()` returns no workbench for some unknown reason, so it's not working there either.

Prompting the user within the ping code will work at least, and I think it is a sound approach. If that is not sufficient, we could place prompting in more places.

**Comment by briandealwis** [comment]
> The sdk.internal Activator is triggered when the Eclipse is being launched. 

Context functions currently cause early activations.

> but PlatformUI.getWorkbench() returns no workbench for some unknown reason, so it's not working there either.

Hmm, that seemed weird so I tried to reproduce… and I see `PlatformUI.getWorkbench()` returning the workbench.

You could have two variants of the send-ping: one suitable for headless situations, and the other for non
