### ISSUE TITLE
Use gcloud for local server

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#14]
What's the gcloud command to run a local dev server?

**Comment by elharo** [comment]
relevant: https://code.google.com/p/googleappengine/issues/detail?id=12119

**Comment by loosebazooka** [comment]
you should be able to just call :
google-cloud-sdk/bin/dev_appserver.py

**Comment by elharo** [comment]
After further investigation, this is not yet possible. We can reopen if it becomes possi9ble in the future.
