### ISSUE TITLE
Develop a list of operations we want to track

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#140]
E.g. 

* Install
* New project wizard generation
* Run local server
* Debug local server
* Deploy

etc.

**Comment by arouzrokh** [comment]
is this client side or server side or both? thanks

**Comment by elharo** [comment]
Primarily client side since that's what we need to write extra code to support. Server side we'll need to collect everything gcloud sends.

**Comment by chanseokoh** [comment]
Had a meeting with @arouzrokh. For collecting raw data, we capture the following events at the moment:

- New Project Wizard: completion
- Deploy action: initiation
- Local run and debug action: initiation
- Login: initiation and completition

**Comment by elharo** [comment]
Please add these to the design doc o a subdoc.

**Comment by chanseokoh** [comment]
Updated the [Analytics section](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/wiki/Cloud-Tools-for-Eclipse-Technical-Design#client-side-usage-tracking-via-google-analytics). Feel free to update further.
