### ISSUE TITLE
Figure out where to load classes from

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#149]
e.g. where do we load appengine-1.0-sdk.19.37.jar

p2 repository?
find on file system?

**Comment by briandealwis** [comment]
There are two types of libraries that we need to figure out:

1. _AE Runtime_: the jars that form the standard AE runtime; these are provided by the AE container  and are excluded from the generated `.war`:
   - In the [AE Java SDK](https://cloud.google.com/appengine/downloads#Google_App_Engine_SDK_for_Java), these are under the `lib/shared` directory:  like `servlet-api.jar`, `jsp-api.jar`, `el-api.jar`

2. _Everything else_: the jars that need to be shipped along; these typically provide bridges to various AE services
   - in the AE Java SDK, these are under the `lib/user` directory:
      - `appengine-api-1.0-sdk-1.9.36.jar`
      - `appengine-api-labs-1.9.36.jar`
      - `libservice.jar`: contains just [_com.google.auto.service.AutoService_](https://github.com/google/auto/tree/master/service) annotation
      - `appengine-jsr107cache-1.9.36.jar`
      - `jsr107cache-1.1.jar`
      - `orm/`: datanucleus

Q: do we expose all of these libraries by default, or do we make them available as an installable facet?  In a Maven world, these libraries are opt-in: the developer has to add an explicit `<dependency>` on them.

**Comment by rdayal** [comment]
I feel like the ones in lib/shared would already be exposed via an installable facet in Eclipse.

As for the ones under lib/user, wouldn't we define a Server Runtime to represent these?

**Comment by rdayal** [comment]
@ludoch as he knows the SDK quite well.

**Comment by briandealwis** [comment]
> I feel like the ones in lib/shared would already be exposed via an installable facet in Eclipse

The _Dynamic Web Project_ facets assume that the libraries are actually pulled in from the server runtime.  Which makes sense since a runtime might actually provide additional complementary functionality (e.g., annotation-driven processing).

So yes, we would define a server runtime, we just need to figure out where and how we want the user to configure those runtimes.

**Comment by rdayal** [comment]
This also seems to be a high priority.

**Comment by rdayal** [comment]
Hey guys - have you figured out where you want to get the App Engine Server runtimes from? Are we going to download them from Maven Central? Are we introspecting the Cloud SDK for them?

**Comment by rdayal** [comment]
(this is something worth driving to a decision on sooner rather than later)

**Comment by ludoch** [comment]
+@ajkannan who can share some massive refactoring we are putting in place there (as well as complete explosion of the SDK via Maven artifacts instead of a big blog zip file for the entire SDK.

**Comment by elharo** [comment]
ATM , there are two answers to this depending on what we're doing:

1. The cloud SDK we locate through app-tools-lib-for-java for our code
2. Call app-tools-lib-for-java instead, and let it worry about its own classpath.

This will likely change as more jars become available in maven, but for the time being this works well.

**Comment by ajkannan** [comment]
While the entire SDK is uploaded to Maven, all the constituent jars necessary for staging and local run should also be on Maven.

In case it's useful, I'm in the process of writing a pom file that lists out the dependencies of the SDK.  It lists dependencies in separate profiles for different purposes.  For example, the jars under "lib/shared" are under the profile "SharedJetty6" ("SharedJetty9" contains extra jars necessary for the App Engine flex local run).  The pom file is definitely not yet ready for consumption yet (and in fact I have some fixes that should go in), but in case you want to take a look, [here](https://repo1.maven.org/maven2/com/google/appengine/appengine-dependencies-sdk/0.0.1/appengine-dependencies-sdk-0.0.1.pom) is a very early draft.  I intend to parse this pom file in a small staging jar to develop a lightweight SDK that doesn't need to be explicitly packaged with all its dependencies.

**Comment by elharo** [comment]
I think this is now fixed.
