### ISSUE TITLE
Fix errors and warnings from generated Maven `appengine-skeleton-archetype`-based projects

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/gcloud-eclipse-tools#150]
Maven-generated `appengine-skeleton-archetype` projects generate an error and warning:
- a warning because no DTD is found for `appengine-web.xml`
- an error as the Netbeans `nbactions.xml` includes `#set` notations in the prolog

We should:
- [ ] Configure a DTD for `appengine-web.xml`.  The DTD is [here](https://googleappengine.googlecode.com/svn/trunk/java/src/main/com/google/appengine/tools/development/appengine-web.xsd).  Add as URI-based contribution via the `org.eclipse.wst.xml.core.catalogContributions` extension point for `http://appengine.google.com/ns/1.0` 
- [ ] Set up a validation exclusion rule for the `nbactions.xml` via the `org.eclipse.wst.validation.exclude` extension point

**Comment by elharo** [comment]
That warning is very questionable for multiple reasons. DTDs are not required in XML, and often aren't a good idea. I need to think about this.

**Comment by briandealwis** [comment]
We have a DTD (it’s provided by the appengine repository).  We’re just hooking it up, and it means we get validation in the XML editor for free.

**Comment by elharo** [comment]
I don't see a DTD. I see an XSD schema. Is that what you meant here?

**Comment by briandealwis** [comment]
> I don't see a DTD. I see an XSD schema. Is that what you meant here?

Yeah, sorry wrong terminology.

**Comment by rdayal** [comment]
I think the DTD warning is not that big a deal. That we can fix as a low pri item.
As for nbactions.xml - why is this being generated? Can we exclude this from being generated? It doesn't seem that useful for us.

**Comment by briandealwis** [comment]
This issue will be fixed as part of #146.  `nbactions.xml` is generated as part of the Maven archetype: it's out of our immediate control.  We could delete it, but the plugin now configures rules to avoid validating  `nbactions.xml` and `appengine-web.xml`.

**Comment by briandealwis** [comment]
Fixed in #146.
