### ISSUE TITLE
Setup the title bar in the new app engine wizard page

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#155]
In the constructor for AppEngineStandardWizardPage

    this.setTitle("Title: App Engine Standard Project");
    this.setDescription("Description: App Engine Standard Project");
    this.setInageDescriptor

**Comment by elharo** [comment]
see here for reading plugin properties from the bundle:

http://stackoverflow.com/questions/3427717/how-can-i-use-properties-taken-from-a-file-in-the-code-of-an-eclipse-pde-fragmen

**Comment by briandealwis** [comment]
The easiest approach to extract strings is to right click on the project or the class and select _Plug-in Tools &rarr; Externalize Strings_

**Comment by elharo** [comment]
That seems to create properties in the current plugin. I want to read the string across plugins, but it looks like a good start
