### ISSUE TITLE
Add rule to ensure we don't link to commons collections 3.2.1

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#16]
http://www.geekinasuit.com/2016/03/apache-commons-collections-321.html

**Comment by kosit-orngsri** [comment]
สวัสดี

**Comment by kosit-orngsri** [comment]
ขอบคุณถ้ามันไม่มีผลกระทบ

2016-03-30 7:12 GMT+07:00 Andras Kerekes <notifications@github.com>:
