### ISSUE TITLE
GAE Standard Runtime needs to set up classpath

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#167]
e.g. include servlet-api.jar like the Generic Server Framework runtime does.

**Comment by rdayal** [comment]
Is this the same as https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/161#issuecomment-219847235

**Comment by elharo** [comment]
No, this isn't. #161 is to create a runtime for the project if one doesn't already exist. 

This bug is that the non-GSF based runtime does not set up the classpath like the GSF based runtime does.

**Comment by elharo** [comment]
*Might* have something to do with CloudSdkFacetInstallDelegate

**Comment by nbashirbello** [comment]
This looks like it has been fixed.

So if you have an Eclipse workspace that doesn't have an App Engine runtime (whether 'App Engine' or 'GAE Standard' runtimes), when you create a new project using either the 'Google App Engine Standard Java Project' option or the 'Maven-based Google App Engine Standard Java Project' option,  the servlet-api.jar and jsp-api.jar are added to the new project's classpath.
