### ISSUE TITLE
com.google.gson vs com.google.code.gson

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#195]
Why are we depending on com.google.gson (which I don't see in Maven central) vs com.google.code.gson? What is the difference between these two?

**Comment by elharo** [comment]
Looks like the Java package com.google.gson has the maven groupId com.google.code.gson

https://github.com/google/gson/tree/master/gson/src/main/java/com/google/gson

However we're using the groupId com.google.gson. Maybe that's whats in orbit?

**Comment by briandealwis** [comment]
I think that's right.  We can pull in dependencies from Maven Central, but I'm not entirely sure we can do that in one-pass and include it in a repo.

**Comment by elharo** [comment]
If we can't easily grab things from Maven central that's going to be a problem for app-tools-lib-for-java and likely other dependencies.

How hard is it to get a library approved for orbit?

**Comment by briandealwis** [comment]
Orbit only hosts bundles that are required by an Eclipse project.  I'll investigate using the version from MC.
