### ISSUE TITLE
maven wizard doesn't generate Java code

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#198]
i.e. no src/main/java folder

May be a simple case of needing to select a different archetype by default.

**Comment by elharo** [comment]
When I change the wizard to use the guestbook archetype instead, it does generate the expected Java code so the issue seems to be that we need a slightly more complex archetype here, if we're going to use archetypes at all.

**Comment by elharo** [comment]
I'm trying to get some code added to the skeleton in https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/pull/23

If that proves problematic, maybe we can get this added as a second skeleton.

**Comment by rdayal** [comment]
Yeah, just hit this. This definitely needs to be fixed.

**Comment by elharo** [comment]
fixed
