### ISSUE TITLE
Offline build

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#202]
In the airport today, I notice that I can't build if my laptop isn't connected to the network because it needs to load the p2 repositories.

If there's a quick and easy fix for this, we should implement it. If it's complicated and will take a significant amount of time, don't bother.

**Comment by briandealwis** [comment]
`mvn -o` should do it.

**Comment by briandealwis** [comment]
Yup, does the trick.
