### ISSUE TITLE
Add dependency on app-tools-lib-for-java

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#209]
We're going to need this for a lot of things so I'm splitting it out into an issue of its own:

https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/

Currently in maven central snapshot but not eclipse repositories

**Comment by briandealwis** [comment]
I started looking at this for #9.  For now we can import it using the _Import Existing Maven_ project and it should do the right thing.

**Comment by elharo** [comment]
By "right thing" do you mean update all the various manifest and pom.xml files as needed to include the dependency or simply include the dependency locally in Eclipse?

**Comment by briandealwis** [comment]
The `app-tools-for-java` uses the `maven-bundle-plugin` to add OSGi metadata to generated `.jar`.  m2e knows how to generate and populate a MANIFEST.MF so that it will be managed by PDE.

**Comment by rdayal** [comment]
Shouldn't this be linked in to the local run milestone?

**Comment by elharo** [comment]
We actually need it for pretty much everything: local run and debug, new application, and deploy. Github doesn't let us assign it more than one milestone though. :-(

@briandealwis This is fixed now, right?

**Comment by rdayal** [comment]
Ah ok. I see. I didn't realize it was already assigned to a milestone. My bad!

**Comment by briandealwis** [comment]
Fixed by #215
