### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#218]
The zip built from head cannot be installed, as near as I can tell.

I think we may need to rollback the change that added dependencies on maven central. It may not be only that we can't run from inside eclipse, but that the plugin no longer works, at all.

![screen shot 2016-06-06 at 7 31 06 pm](https://cloud.githubusercontent.com/assets/1005544/15841234/8b625ff4-2c1d-11e6-884c-4e9728cb7266.png)

@briandealwis If you can get to this ASAP, please do so. Otherwise I'll experiment with a rollback tomorrow morning. If a rollback will fix this, please do that first, before working on a fix for the issue.

**Comment by briandealwis** [comment]
The underlying problem is that `c.g.c.t.eclipse.appengine.localserver` depends on `c.g.c.t.eclipse..appengine.ui` which wasn't included in the `c.g.c.t.eclipse.suite.e4.feature` feature.

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Google Cloud Platform for Eclipse 4.5 0.1.0.201606080223 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201606080223)
  Missing requirement: GCloud for Eclipse App Engine Local Server 0.1.0.201606080223 (com.google.cloud.tools.eclipse.appengine.localserver 0.1.0.201606080223) requires 'bundle com.google.cloud.tools.eclipse.appengine.ui 0.1.0' but it could not be found
  Cannot satisfy dependency:
    From: Google Cloud Platform for Eclipse 4.5 0.1.0.201606080223 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201606080223)
    To: com.google.cloud.tools.eclipse.appengine.localserver [0.1.0.201606080223]
```
