### ISSUE TITLE
"Run As -> Server" option missing from GAE projects

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/gcloud-eclipse-tools#222]
Projects created with the "Google App Engine Standard Java Project" wizard and the "Maven-based Google App Engine Standard Project" wizard are missing the Server running option under the context menu "Run As".

**Comment by rdayal** [comment]
I think this happens if you don't have the Eclipse JEE version installed.

You can either download that version of Eclipse, or install the Eclipse JEE tooling from the Eclipse update site.
