### ISSUE TITLE
Running "mvn package" in the root directory results in build failure

### ISSUE THREAD

**Issue by rdayal** [GoogleCloudPlatform/gcloud-eclipse-tools#233]
If I 'git clone' the repo, and then enter the directory and run:

mvn package

I get the following error:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] trunk .............................................. SUCCESS [  5.391 s]
[INFO] Apache Standard License v2 ......................... SUCCESS [  0.409 s]
[INFO] com.google.cloud.tools.eclipse.3rdparty.feature .... SUCCESS [  0.118 s]
[INFO] com.google.cloud.tools.eclipse.appengine.ui ........ FAILURE [  5.033 s]
[INFO] com.google.cloud.tools.eclipse.appengine.localserver SKIPPED
[INFO] com.google.cloud.tools.eclipse.appengine.newproject  SKIPPED
[INFO] com.google.cloud.tools.eclipse.appengine.newproject.maven SKIPPED
[INFO] com.google.cloud.tools.eclipse.appengine.whitelist . SKIPPED
[INFO] com.google.cloud.tools.eclipse.suite.e45.feature ... SKIPPED
[INFO] google-cloud-plugin-eclipse.repo ................... SKIPPED
[INFO] com.google.cloud.tools.eclipse.test.dependencies ... SKIPPED
[INFO] com.google.cloud.tools.eclipse.appengine.localserver.test SKIPPED
[INFO] com.google.cloud.tools.eclipse.appengine.whitelist.test SKIPPED
[INFO] com.google.cloud.tools.eclipse.appengine.newproject.test SKIPPED
[INFO] com.google.cloud.tools.eclipse.appengine.newproject.maven.test SKIPPED
[INFO] com.google.cloud.tools.eclipse.appengine.ui.test ... SKIPPED
[INFO] com.google.cloud.tools.eclipse.usagetracker ........ SKIPPED
[INFO] com.google.cloud.tools.eclipse.usagetracker.test ... SKIPPED
[INFO] gcp-eclipse-mars ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:49 min
[INFO] Finished at: 2016-06-12T14:19:59-04:00
[INFO] Final Memory: 150M/907M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project com.google.cloud.tools.eclipse.appengine.ui: useJDK = BREE configured, but no toolchain of type 'jdk' with id 'JavaSE-1.7' found. See http://maven.apache.org/guides/mini/guide-using-toolchains.html -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.google.cloud.tools.eclipse.appengine.ui

Note that I have not run the step to build the target platform (due to https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/232). Seems unrelated though.

**Comment by rdayal** [comment]
Ah, never mind, I see that there is information on what to do in "Configuring Maven/Tycho Builds" under README.md.

Perhaps we should move this information higher up in the README.md text.

**Comment by elharo** [comment]
done
