### ISSUE TITLE
When installing from locally-built repo, 3rd-party features item appears under "Uncategorized"

### ISSUE THREAD

**Issue by rdayal** [GoogleCloudPlatform/gcloud-eclipse-tools#234]
After successfully building the code locally, I installed the plugin from the local archive. I see the following update site info:

![screen shot 2016-06-12 at 3 16 47 pm](https://cloud.githubusercontent.com/assets/3709554/15993345/ba438932-30b0-11e6-8e2c-f433ae63a1ed.png)

"Cloud Tools for Eclipse" category - should it be called "Google Cloud Tools for Eclipse", or just "Google Cloud Platform"?

Underneath,  the item should probably be called "Cloud Tools for Eclipse".

I also see "Uncategorized", and an item under there called "3rd party features". Is that going to remain in the final version? Is the installation of these really optional?

**Comment by elharo** [comment]
@arouzrokh Would you rather "Google Cloud Tools for Eclipse" or ""Google Cloud Platform"? It's a one-line fix. Just let me know which you prefer.

**Comment by briandealwis** [comment]
This feature was a workaround dependencies not being included, but I just noticed this morning that aren't setting `includeAllDependencies=true`.

**Comment by briandealwis** [comment]
Previously these uncategorized items weren't shown.

**Comment by briandealwis** [comment]
Hmm, we were explicitly selecting items to pull in to avoid pulling in `org.eclipse.*`.

**Comment by briandealwis** [comment]
The 3rdparty feature gathers together external dependencies that aren't easily obtainable from standard p2 repositories, like the bundles we pull from Maven Central.  But we can pull in this feature using a .product definition, which is not shown with the _Install New Software_ dialog.
