### ISSUE TITLE
in the new py based dev server, the admin console is 8000 not a sub url under /_ah/admin

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/gcloud-eclipse-tools#236]
Using Run As -> Run on Server -> App Engine Standard on maven Google App Engine projects fails

**Comment by briandealwis** [comment]
@nbashirbello: What failure are you seeing?  It works in my testing.

**Comment by nbashirbello** [comment]
I get the follwoing error when opening the admin console on a maven project with App Engine support:

HTTP ERROR 500

Problem accessing /_ah/admin. Reason:

    com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate cannot be cast to com.google.appengine.tools.development.ApiProxyLocal
Caused by:

java.lang.ClassCastException: com.google.appengine.tools.development.devappserver2.DevAppServer2Delegate cannot be cast to com.google.appengine.tools.development.ApiProxyLocal
	at com.google.apphosting.utils.servlet.DatastoreViewerServlet.init(DatastoreViewerServlet.java:124)
	at javax.servlet.GenericServlet.init(GenericServlet.java:212)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:339)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
.....

**Comment by charlescapps** [comment]
I'm seeing this same error when running from the terminal using the `gcloud-maven-plugin` with `mvn gcloud:run`

**Comment by charlescapps** [comment]
However, the admin console is working on port :8000, I guess the `/_ah/admin` is just deprecated... ?

**Comment by ludoch** [comment]
Correct, in the new py based dev server, the admin console is 8000 not a
sub url under /_ah/admin
We did not 100% cleanup this Java process.

**Comment by elharo** [comment]
So this is a gcloud bug, then? Where do I file that?

**Comment by elharo** [comment]
Bug has been reported into gcloud. Closing here since the bug is not part of this code base.

**Comment by elharo** [comment]
b/30138110
