### ISSUE TITLE
Local server run should rely on app-tools-lib-for-java to execute DevAppServer

### ISSUE THREAD

**Issue by rdayal** [GoogleCloudPlatform/gcloud-eclipse-tools#242]
Right now, there are three different ways that the DevAppServer could get executed

1) App Engine - Custom Runtime
2) App Engine - Generic Server Framework
3) Pure Maven. Defined as:
---->Run As > Run Configurations
---->Maven Build > DevAppServer
---->Click the Run button
---->Load http://localhost:8080 in browser.

In cases 1) and 2) , we are running the dev_appserver.py ourselves by locating the script and shelling out to it. 

In case 3), the user is running Maven directly.

We should really collapse 1) and 2) down so that they use the app-tools-lib-for-java to invoke the DevAppServer (may require changes to app-tools-lib-for-java). 3) will remain as-is, as the user is always free to execute Maven goals directly from the IDE if they wish to.

**Comment by nbashirbello** [comment]
Done in #273 and #308
