### ISSUE TITLE
Could not resolve module: org.eclipse.compare.win32

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#245]
When launching eclipse from eclipse we see this in the console:

!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.compare.win32 [2478]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=win32)"

Figure out if this is worth addressing and fixing.

**Comment by elharo** [comment]
Perhaps relevant: https://bugs.eclipse.org/bugs/show_bug.cgi?id=411046#c7

"This seems to indicate that you have two versions of some bundles in your target.  In particular org.eclipse.compare.win32 is causing issues."

**Comment by briandealwis** [comment]
Just ignore it.  You'll see this if you have a launch configuration with _run with all plugins_ or if you select a platform-specific bundle/fragment that isn't appropriate for your platform.
