### ISSUE TITLE
Debugging appengine:devserver does not appear to work

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/gcloud-eclipse-tools#249]
Launching a generated _Maven-Based Google App Engine StandardProject_ using the  _Debug As &rarr; DevAppServer_ does not appear to the user to work: although activity is seen in the debugger, no breakpoints are triggered.  This `DevAppServer.launch` launch configuration is generated by the `com.google.appengine.archetypes:appengine-skeleton-app` archetype.

The underlying problem is that running a Maven build target in Debug mode actually attaches to the Maven instance itself, and is intended to debug Maven plugins.  But `appengine:devserver` executes the `dev_appserver` in a separate process, and the Eclipse debugger needs to be somehow directed to attach to that JVM instead.

The recommended approach in the [AE docs](https://cloud.google.com/appengine/docs/java/tools/maven#development_server_goals), and described on [stackoverflow](http://stackoverflow.com/a/14142536/600339), requires modifying the `pom.xml` to add a `<jvmFlags>` element and then connecting a _Remote Java Application_ configuration to that instance.

**Comment by elharo** [comment]
Moving to low priority since current plans are that this is not the primary way we'll run and debug.

**Comment by briandealwis** [comment]
As we support launching the `dev_appserver` directly, and this works for Maven-based projects too, we could update the archetype to restrict the `DevAppServer.launch` to only work in Run mode. This is done by adding an attribute to the `.launch` like the following:

```
<setAttribute key="org.eclipse.debug.core.LAUNCH_MODES">
    <setEntry value="run"/>
</setAttribute>
```

Although the launch config will appear in the Debug Configurations dialog, it cannot be run.  I'll file a bug against https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java to add this.  The error shown in Eclipse somewhat obscure ([filed a bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=496184) to improve this against Eclipse/Debug).

**Comment by briandealwis** [comment]
I don't see any way to make this work better from the tooling side, so I'll close this.
