### ISSUE TITLE
Set up gcloud on Travis

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#267]
so that everything that depends on it including PathResolver works

**Comment by elharo** [comment]
https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step

**Comment by elharo** [comment]
https://github.com/GoogleCloudPlatform/app-maven-plugin/blob/66f65802944851c269985bc68313e430a40d78ed/.travis.yml

has an example of how to install gcloud in a travis environment

**Comment by briandealwis** [comment]
Cool.  What do we need to do to create an account?

**Comment by elharo** [comment]
We have an account. Not sure if you have access to configure it though. I should probably take this one.
