### ISSUE TITLE
Work with non-default VM 

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#28]
Build instructions say:

"Set the checkbox selected for the JDK you just added to mark it as default."

We should figure out how to make this work without making JDK 7 the default since users may want to use a different JDK for other projects

**Comment by briandealwis** [comment]
That’s a good point.  The other way is to install the PDE Execution Environments (below) and enable API scanning on our projects.  The way to verify the EEs is Preferences > Plug-in Development > API Errors/Warnings > API Use and check for the Execution Environment Descriptions.  If no descriptions are installed, there should be a button to prompt for their installation.  Oh, and we should also mark ‘Reference not defined in specified execution environment’ as an error.

**Comment by akerekes** [comment]
Or we can just get rid of that line as it is not necessary to mark the JDK to be default.

**Comment by briandealwis** [comment]
> Or we can just get rid of that line as it is not necessary to mark the JDK to be default.

Good point. :+1: 

I was thinking this was for user docs for developing for GAE.

**Comment by elharo** [comment]
Sure, if it's not actually necessary get rid of the line.

**Comment by akerekes** [comment]
Docs updated.
