### ISSUE TITLE
Minimal Deploy

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#283]
Given how app-tools-lib-for-java is designed, I think we can kick off deployment without solving login first. Specifically, I think we can do these tasks:

1. New deploy plugin. This does nothing but does not include a basic XmlTest for the plugin.xml.
1. Make the plugin add a "Deploy to AppEngine" context menu item on all projects.
1. Limit the menu item to appearing only on projects with the app engine facet.
1. Export the exploded WAR file to a staging directory
1. Call staging operation via CloudSDK
1. Use app-tools-lib-for-java to deploy the project, assuming the user has logged in at the command line in the gcloud cli.
1. Cleanup previous deploy work directories.

Note that as tasked out here this is at least 4 separate PRs.

Later (or in parallel) we can add in IDE login that will be used instead.

Thoughts?

**Comment by patflynn** [comment]
seems reasonable.

**Comment by akerekes** [comment]
All tasks have been implemented.
