### ISSUE TITLE
One Google Cloud Platform for Eclipse Mars target

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#29]
Whehn we setup a build we get two "Google Cloud Platform for Eclipse Mars" targets, though they're actually the same. 

Set the checkbox next to one of the `Google Cloud Platform for Eclipse Mars`
     target platforms (they are pointing to the same file), and click `Apply`.

See if we can figure out how to have only one.

**Comment by briandealwis** [comment]
This comes as all files come in both from the ’trunk’ project as well as the eclipse-mars project.  I think there’s a way to exclude files from nested containers, but I don’t remember how at the moment.

**Comment by briandealwis** [comment]
I thought there was a general resource filter to filter children contained in nested projects, but it's specific to the [Open Resources dialog](https://bugs.eclipse.org/bugs/show_bug.cgi?id=460749).

We can add a resource filter on the `trunk` project to exclude files in the `plugins/`, `features`, and `eclipse/{neon,mars}` directories.
