### ISSUE TITLE
Alternate ports

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#291]
Make it possible to configure and run the development server on other ports

**Comment by elharo** [comment]
Don't forget to update the DefaultStopConfiguration in

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java:

when we do this.

**Comment by nbashirbello** [comment]
They are duplicates. Closed #300

**Comment by elharo** [comment]
This is a duplicate of #259
