### ISSUE TITLE
Ability to edit folder settings of local server

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#3]
When we create an app engine local dev server we need to define a few libraries (work directory, location of appengine-web.xml, etc). Once the server is created, currently there is no way to change/view these settings (apart from possibly digging into config files and manually change them). It would be better to e.g. add them to the editor that is opened when the user right clicks on the server (in the Servers view) and selects 'Open' option.

**Comment by elharo** [comment]
obsolete now that GSF is gone
