### ISSUE TITLE
Can we use gcloud devappserver to run Java apps?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#31]
https://cloud.google.com/sdk/gcloud-app#Running_locally

This seems to require app.yaml.

Perhaps after staging?

**Comment by elharo** [comment]
https://cloud.google.com/appengine/docs/java/tools/uploadinganapp#staging_yaml_files

**Comment by loosebazooka** [comment]
Yeah there doesn't seem to much documentation around this yet, but it appears an app.yaml is required and the easiest way to convert an exploded-war appengine application into something that is readable by the dev_appserver.py is using stage.

**Comment by elharo** [comment]
Staging requires the appengine Java SDK so even if this solves our problem, it does not remove our dependence on the appengine Java SDK:

./appengine-java-sdk/bin/appcfg.sh stage <WAR-dir> <yaml-dir>

**Comment by elharo** [comment]
OK, looks like we don't have to stage:

$ dev_appserver.py war

However:


Are you running with Java 8? I think that would explain it. We should improve the experience here, but we don't support using Java 8 to run GAE Java apps in the dev app server.

2016-03-24 12:56 GMT-07:00 ludovic Champenois <ludo@google.com>:

Adding Eamonn....
I remember some issue there depending on the JDK used...
Ludo

On 3/24/16 12:35 PM, Appu Goundan wrote:
Is this a known issue?

When I run a java application with the dev_appserver.py (from cloudSDK), I get a weird error if I run an application when I don't set <vm>true</vm> in appengine-web.xml, but with <vm>true</vm> everything seems to work fine. Any ideas here? Output below..

**Comment by elharo** [comment]
The answer seems to be yes, possibly given:

* Java 7, not Java 8
* set <vm>true</vm> in appengine-web.xml,
