### ISSUE TITLE
setup update site

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#339]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Google Cloud Platform for Eclipse 4.5 0.1.0.201607111634 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201607111634)
  Missing requirement: GCloud for Eclipse App Engine Local Server 0.1.0.201607111634 (com.google.cloud.tools.eclipse.appengine.localserver 0.1.0.201607111634) requires 'bundle com.google.cloud.tools.eclipse.sdk 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Google Cloud Platform for Eclipse 4.5 0.1.0.201607111634 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201607111634)
    To: com.google.cloud.tools.eclipse.appengine.localserver [0.1.0.201607111634]

**Comment by elharo** [comment]
artifacts.xml seems to have the correct version:

   <artifact classifier='osgi.bundle' id='com.google.cloud.tools.eclipse.sdk' version='0.1.0.201607121132'>
      <properties size='5'>
        <property name='artifact.size' value='10414'/>
        <property name='download.size' value='10414'/>
        <property name='maven-groupId' value='com.google.cloud.tools.eclipse'/>
        <property name='maven-artifactId' value='com.google.cloud.tools.eclipse.sdk'/>
        <property name='maven-version' value='0.1.0-SNAPSHOT'/>
      </properties>
    </artifact>

**Comment by elharo** [comment]
content.xml, however, does show 0.0.0 on java.package:

    <unit id='com.google.cloud.tools.eclipse.sdk' version='0.1.0.201607121132'>
      <update id='com.google.cloud.tools.eclipse.sdk' range='[0.0.0,0.1.0.201607121132)' severity='0'/>
      <properties size='5'>
        <property name='org.eclipse.equinox.p2.name' value='Support for Google Cloud SDK within the Eclipse IDE'/>
        <property name='org.eclipse.equinox.p2.provider' value='Google, Inc.'/>
        <property name='maven-groupId' value='com.google.cloud.tools.eclipse'/>
        <property name='maven-artifactId' value='com.google.cloud.tools.eclipse.sdk'/>
        <property name='maven-version' value='0.1.0-SNAPSHOT'/>
      </properties>
      <provides size='5'>
        <provided namespace='org.eclipse.equinox.p2.iu' name='com.google.cloud.tools.eclipse.sdk' version='0.1.0.201607121132'/>
        <provided namespace='osgi.bundle' name='com.google.cloud.tools.eclipse.sdk' version='0.1.0.201607121132'/>
        <provided namespace='java.package' name='com.google.cloud.tools.eclipse.sdk' version='0.0.0'/>
        <provided namespace='java.package' name='com.google.cloud.tools.eclipse.sdk.internal' version='0.0.0'/>
        <provided namespace='org.eclipse.equinox.p2.eclipse.type' name='bundle' version='1.0.0'/>
      </provides>

Now where does that come from?

**Comment by briandealwis** [comment]
We're not versioning our packages, and so the default version is 0.0.0.
