### ISSUE TITLE
maven directory in jar

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#341]
surprisingly our jar files in the update site include the maven files like pom.xml:

     0 Mon Jul 11 17:33:26 EDT 2016 META-INF/maven/
     0 Mon Jul 11 17:33:26 EDT 2016 META-INF/maven/com.google.cloud.tools.eclipse/
     0 Mon Jul 11 17:33:26 EDT 2016 META-INF/maven/com.google.cloud.tools.eclipse/com.google.cloud.tools.eclipse.appengine.localserver/
   703 Fri Apr 08 13:31:08 EDT 2016 META-INF/maven/com.google.cloud.tools.eclipse/com.google.cloud.tools.eclipse.appengine.localserver/pom.xml
   176 Mon Jul 11 17:33:26 EDT 2016 META-INF/maven/com.google.cloud.tools.eclipse/com.google.cloud.tools.eclipse.appengine.localserver/pom.properties

Is this actually needed or can/should we strip it out?

**Comment by briandealwis** [comment]
Not needed and it [can be omitted](https://dev.eclipse.org/mhonarc/lists/tycho-user/msg04248.html) with:
```
  <build>
    <pluginManagement>
        <plugin>
          <groupId>org.eclipse.tycho</groupId>
          <artifactId>tycho-packaging-plugin</artifactId>
          <version>${tycho-version}</version>
          <configuration>
            <archive>
              <addMavenDescriptor>false</addMavenDescriptor>
            </archive>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
```

**Comment by briandealwis** [comment]
Closing this as it seems to be common for maven projects.
