### ISSUE TITLE
Upgrading Appengine SDK breaks project

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#35]
I generate a new web application project using the plugin. It depends on AppEngine SDK 1.9.30. after fixing the project setup to use jdk7, it compiles and deploys to App engine successfully. The 1.9.30 SDK is displayed as plugin and also as local directory from my $HOME, both are valid.
Then I upgrade the App Engine SDK bundle plugin to 1.9.34 from custom update site. It installs successfully.
When I restart Eclipse, the project still displays 1.9.30 as it's dependency, but Eclipse complains that it does not have any App Engine SDK on its build path, and also no SDK from bundle is displayed among the available SDKs.

![image](https://cloud.githubusercontent.com/assets/3378942/14080922/e167894e-f4d5-11e5-9a8a-f6d1d5477066.png)

![image](https://cloud.githubusercontent.com/assets/3378942/14080965/12795d82-f4d6-11e5-829d-095f1e5b6531.png)

**Comment by akerekes** [comment]
When the project is generated, in its properties under `Google/App Engine` both SDKs from my $HOME and the installed plugin are displayed. After restarting Eclipse, only the SDK from my $HOME is visible. But no error, possibly because it is the same version (1.9.30) as the project was created with and the plugin contained.

**Comment by akerekes** [comment]
If I continue with the previous project, and upgrade the SDK plugin to 1.9.34, and set it for the project, it'll depend on 1.9.34, and deploys successfully.
Restarting Eclipse again leads to the error of missing SDK, but this time it is still visible in the `Properties`. If I select the SDK from $HOME, click `OK`, the error markers disappear. Then setting the App Engine SDK to 1.9.34 from the plugin again will not lead to errors.
Restarting Eclipse results in the above error again.
It looks like the SDK is not properly resolved during the build after restart, but it's valid and can be used after changing it to other version and back.

**Comment by akerekes** [comment]
Wrong repo!

**Comment by briandealwis** [comment]
I'm glad you figured it out, but I'm unclear why this would be caused by the wrong repo.

It does point out one UX issue: if the user updates their via the p2 update site (as compared to adding a new SDK that points to something they downloaded), then we may have projects that point to a stale SDK that may no longer exist (e.g., the 1.9.30 in your example above).  Perhaps we should scan projects on restart or after an update and prompt the user to update if any are found pointing to non-existent SDKs.
