### ISSUE TITLE
Create core bundle

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#350]
Create a core bundle that can contain common/utility classes that are used throughout the plugin, e.g.: common helper classes to wrap Eclipse's SDK to allow unit testing

**Comment by elharo** [comment]
I might call it util instead of core, but either way this is a good idea. We may need a separate bundle for test-only code that shouldn't find its way into the plugin binary.

**Comment by akerekes** [comment]
#372 #371
