### ISSUE TITLE
console in app-tools-lib-for-java

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#357]
2 likely related issues when running with the app-tools-lib-for-java:

1. If the console is not showing when you launch, it does not auto-open.
2. The console does not provide the red stop square used to kill the server.

Both of these work with the custom runtime.

**Comment by elharo** [comment]
3. Even after exiting Eclipse the server is still running and responding.

**Comment by nbashirbello** [comment]
Fixed with #361
