### ISSUE TITLE
Missing App Engine facet functionality

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/gcloud-eclipse-tools#360]
App Engine Facet is missing the following features:
- installing the facet should configure the project to have the GAE runtime as the primary runtime (if a GAE runtime does not exist, a new one should be created)
- uninstalling the facet should remove the GAE runtime as the primary runtime
- the facet should limit runtime support of only App Engine Standard runtime
- wiki page should be updated with facet functionality

**Comment by elharo** [comment]
Agree with 1 and 4. I'm not sure why uninstalling the facet should necessarily remove the runtime; and I'm not sure I follow what "facet should limit runtime support of only App Engine Standard runtime" means for the functionality.

**Comment by nbashirbello** [comment]
In regards to point 2 (uninstalling the facet should remove the GAE runtime as the primary runtime):

Adding an App Engine facet to a project means that the project wants App Engine support which means they want to be able to run/debug their project with the dev app server and deploy to App Engine. If the App Engine facet is removed from a project, that means that the project no longer needs to be run on the dev app server which means that the project has no need for the App Engine runtime.

Removing the GAE runtime as the primary runtime means that GAE is not the default runtime for that project, which when the facet is uninstalled is correct. 

After more thought, I think the GAE runtime should not only be removed as the primary runtime, but the GAE runtime should only be compartable with projects that have the GAE facet. 

In regards to point 3 (the facet should limit runtime support of only App Engine Standard runtime):

After more thought, I think that should be removed because one of the big things for the App Engine 'reboot' was flexibility. In other words, the user should be able to use GAE runtime if they want (by installing the App Engine facet) but should be able to use other runtimes too.

**Comment by elharo** [comment]
Is this a superset of #254 ?

**Comment by nbashirbello** [comment]
The last point is kind of opposite of #254, meaning that a project with the GAE facet can use the GAE runtime and any other runtimes they choose. I am leaning more towards this because it is more flexible and also, I can't see it causing any problems. 

I also should mention, that installing a GAE facet could also lead  to the creating of an appengine-web.xml file if it doesn't already exist

**Comment by chanseokoh** [comment]
For your last point of generating appengine-web.xml, perhaps we need to identify if a project is standard or flexible. For flex, we generate app.yaml then?

**Comment by nbashirbello** [comment]
My current thinking is that there should be different facets for GAE Standard and Flex mainly because they have different requirements e.g java 7 vs 8, so one project cannot support both standard and flex

**Comment by nbashirbello** [comment]
Just wanted to note that uninstalling the facet would not delete the appengine-web.xml.
