### ISSUE TITLE
Refactor current AppEngineFacet feature

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/gcloud-eclipse-tools#377]
This involves the following:
- move AppEngineFacet from com.google.cloud.tools.eclipse.appengine.newproject to com.google.cloud.tools.eclipse.appengine.facets
- create Action ids for AppEngineFacet install and uninstall actions
- move AppEngineFacet#installAppEngineFacet and AppEngineFacet#installAppEngineRuntime into FacetInstallDelegate and use ProjectFacetsManager#getActionDefinition  to install and uninstall the facet within the code (using ActionDefinition#getDelegate)
- rename facet to AppEngineStandardFacet

**Comment by nbashirbello** [comment]
@elharo @briandealwis

**Comment by chanseokoh** [comment]
As part of this refactoring, how about renaming it to AppEngineStandardFacet as you mentioned in https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/360#issuecomment-233023946?
