### ISSUE TITLE
Path -> File --> Path Cleanup

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#381]
The PR https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/pull/378 was used to fix API incompatibilities with CloudSdk. The fix was to use Path instead if File when creating CloudSdk.Builder(). However in some cases we start out with a Path, that was converted to a File and the fix converted it back to a Path, this should be cleaned up.

**Comment by akerekes** [comment]
Obsolete. Some of the affected code has been deleted, some has already been cleaned up.

**Comment by briandealwis** [comment]
João cleaned up a lot of that #335
