### ISSUE TITLE
Add same GAE SDK to the classpath than GPE was adding before

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/gcloud-eclipse-tools#385]
Right now, we're only adding three jars (appengine-tools-api.jar, servlet-api.jar and jsp-api.jar) to the classpath, so that newly created projects compile without errors (I suspect).

We should add the same jars as GPE did so non-Maven or non-Gradle projects don't have to manually import missing libraries (e.g., Datastore, etc.).

We should also start providing the gcloud-java SDK for Flex apps, either from the Eclipse new software page or through gcloud.

**Comment by elharo** [comment]
There are some jars GPE added we want to *not* add (e.g. datatstore). We need to got through them one-by-one and decide in each case.

**Comment by briandealwis** [comment]
Would it make sense to make them individual facets?

**Comment by joaoandremartins** [comment]
One idea is to simply have commlib returning a list of all jars that comprise the SDK, and remove the getJarPath() method we recently added.
I don't think Eclipse needs these jars for anything else. But one thing I don't understand is in what ServletClasspathProvider and AppEngineSdkClasspathContainer differ.

They're both adding to a project's classpath, but is it that the latter *is* the classpath that should be provided by the former?

**Comment by elharo** [comment]
Here's a picture from Salman showing what he added manually:

![image](https://cloud.githubusercontent.com/assets/1005544/17062378/ba39b0aa-5000-11e6-9662-234a316359a6.png)

Not sure whether we need all these but it might be a good place to start.

**Comment by briandealwis** [comment]
I can't find `libservice.jar` in the Cloud SDK

**Comment by chanseokoh** [comment]
Yeah, I can't find it either. I find it's in the App Engine SDK.

**Comment by joaoandremartins** [comment]
What I would really like to see here is a replacement for commlib's `CloudSdk.getJarPath()` called `getClasspathJars()` or so that provides all jars required to run an app on GAE. That would be used both in Eclipse and IJ.

**Comment by briandealwis** [comment]
`libservice.jar` contains the [AutoService](https://github.com/google/auto/tree/master/service) annotation (`@com.google.auto.service.AutoService`).

The current implementation of `CloudSdk#getJarPath()` is too inflexible: we shouldn't need to cut a new release because the actual Cloud SDK distribution included a new jar or moved a jar internally.  Rather than a fixed set of jars, perhaps it could try lookups in a few pre-vetted locations?
