### ISSUE TITLE
Add verify-feature-completeness settings

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#387]
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	build/verify-feature-completeness/.project
	build/verify-feature-completeness/.settings

**Comment by chanseokoh** [comment]
Team, I didn't bring my laptop to my home, so I'm writing it here. I'll take a day-off today. I feel occasional physical pain or strain inside my head since yesterday morning. @elharo, could you send an email to our entire team on behalf of me that I'm off? Thanks.
