### ISSUE TITLE
Enable persisting and reusing credentials for Google login

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-eclipse-tools#397]
Created credentials should be managed in a persistent credential datastore for reuse.

For #342.

**Comment by chanseokoh** [comment]
We now have basic functionality for this. But I would like investigate more about refreshing expired credentials and ways to manage them.

**Comment by patflynn** [comment]
Are you not using the existing login library that stores the creds in a
java prefs file?

**Comment by chanseokoh** [comment]
@patflynn No we don't use the library.

I am about to do some investigation, but I wonder if we can avoid storing them in a file entirely. For now, keeping them in memory seems to work in our use cases. Making users log in again after restarts seems reasonable. Perhaps I am missing something.

**Comment by patflynn** [comment]
Forcing the user to login every time they restart Eclipse is definitely not
something we want to force the user to do.

**Comment by patflynn** [comment]
Why aren't we using the library? Wasn't it initially written for GPE?

**Comment by chanseokoh** [comment]
I recently became aware of the existence of the library. Now that I know it, I also have the same question if we need to switch to use the library. We could discuss this with @elharo and @briandealwis. I am fine with either direction.

**Comment by patflynn** [comment]
Sounds good. Can you schedule something?

**Comment by chanseokoh** [comment]
@patflynn I noticed that our IntelliJ plugin requires logging in again after each restart.

**Comment by briandealwis** [comment]
FYI: GPE doesn't use a library to store the token, and [uses Java Preferences directly](https://github.com/GoogleCloudPlatform/google-plugin-for-eclipse/blob/master/plugins/com.google.gdt.eclipse.login/src/com/google/gdt/eclipse/login/GoogleLoginPrefs.java).

**Comment by patflynn** [comment]
You might be seeing that in development if you do a clean build each time.
If you don't clean you'll find that login is persisted across IDE sessions.

**Comment by chanseokoh** [comment]
I am going to save a single credential (actually, a refresh_token) via the standard Java Preferences.

To recap:

- GPE uses [Java Preferences to save a credential](https://github.com/GoogleCloudPlatform/google-plugin-for-eclipse/blob/master/plugins/com.google.gdt.eclipse.login/src/com/google/gdt/eclipse/login/GoogleLoginPrefs.java).
- IntelliJ uses [Java Preferences too](https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/master/google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginPrefs.java#L68).
- The ide-login library doesn't provide any utility for saving credentials. I'll have to implement on my own, using GPE and IntelliJ implementations as references.
- For our use cases so far, we don't need to save access tokens. IntelliJ saves refresh tokens only. So, I'll save a refresh token only.

**Comment by elharo** [comment]
Would it make sense to build this functionality into the ide-login library? If it doesn't need any Eclipse specific work and could be shared with Intellij, that would be spectacular.

**Comment by chanseokoh** [comment]
@elharo It can be done as long as we use Java Preferences. It's not clear if IntelliJ can share it later though; since the ide-login doesn't support managing multiple accounts, IntelliJ uses the ide-login in a non-standard manner and the code to persist credentials in IntelliJ is coupled with that unique design.

I'll create a PR against the ide-login library once it's ready.
