### ISSUE TITLE
Editing an existing runtime environment should have appropriate title

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#4]
The dialog which is shown when the user wants to edit the runtime environment of an app engine local dev server has the title 'New App Engine Runtime', however it would be better to show 'Edit App Engine Runtime'. To open the dialog:
- open the Server view
- right click on the dev server instance
- select Open from the menu
- click on the link 'Runtime Environment'

**Comment by elharo** [comment]
This might be an issue for the Eclipse WTP instead of us.

**Comment by akerekes** [comment]
Confirmed, this is indeed an issue with Eclipse WTP. I'll file a bug about it.

**Comment by elharo** [comment]
Sounds good. Add the link to the bug here when you file it, then close this issue.

**Comment by akerekes** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=490924
