### ISSUE TITLE
Unable to find feature.xml in directory: /Users/elharo/gcloud-eclipse-tools/eclipse/ide-target-platform/target/repository/features/

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#422]
Not sure how significant this is, but just noticed that when running inside the IDE with the plugin we get a couple of dozen error log entries like this:

Unable to find feature.xml in directory: /Users/elharo/gcloud-eclipse-tools/eclipse/ide-target-platform/target/repository/features/org.eclipse.platform_4.5.2.v20160212-1500.jar

This is repeated for various other jars we're importing.

**Comment by briandealwis** [comment]
It's not significant.  The _Directory_-based target platform that we've switched to with `ide-target-platform` is using a p2 repo as an installation.  Works fine for bundles, but features are normally exploded on disk.

We may be able to use one of the other types (_Installation_ perhaps).
