### ISSUE TITLE
Plugin installation fails on Eclipse 4.6 Standard Edition

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcloud-eclipse-tools#428]
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Google Cloud Platform for Eclipse 4.5 0.1.0.201607221535 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201607221535)
  Missing requirement: GCloud for Eclipse App Engine Local Server 0.1.0.201607221535 (com.google.cloud.tools.eclipse.appengine.localserver 0.1.0.201607221535) requires 'bundle org.eclipse.m2e.wtp 1.2.1' but it could not be found
  Cannot satisfy dependency:
    From: Google Cloud Platform for Eclipse 4.5 0.1.0.201607221535 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201607221535)
    To: com.google.cloud.tools.eclipse.appengine.localserver [0.1.0.201607221535]
```

Would it be possible to pull in the dependencies through the plugin installation workflow? @briandealwis

**Comment by meltsufin** [comment]
Note that as a workaround, you can install Web Tools by using this update site:
http://download.eclipse.org/webtools/repository/neon/

**Comment by briandealwis** [comment]
That should have been picked up automatically.  Did you have the 'Contact all update sites' button enabled?

<img width="666" alt="screen shot 2016-07-22 at 12 58 23 pm" src="https://cloud.githubusercontent.com/assets/202851/17064748/1d52ad08-500c-11e6-9adb-bff7a335ab35.PNG">

By default Eclipse installations enable _Contact all update sites_ and should have the release update site configured (`http://download.eclipse.org/releases/mars` or `/neon`), which will have _M2Eclipse_ and _M2Eclipse-WTP_.

**Comment by briandealwis** [comment]
> @meltsufin: Note that as a workaround, you can install Web Tools by using this update site:
http://download.eclipse.org/webtools/repository/neon/

I checked and `org.eclipse.m2e.wtp` is available from both `/releases/mars` and `/releases/neon`.  I tested on a clean Neon installation and was able to install.  I'll add a note about the _Contact all update sites_.

**Comment by briandealwis** [comment]
Done.

**Comment by meltsufin** [comment]
Indeed, I might've had it unchecked. I got it installed now. Thanks.
