### ISSUE TITLE
Remove the "unsigned content" warning

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/gcloud-eclipse-tools#441]
I'm getting the following warning when installing the plugin:

![screenshot from 2016-07-25 10 50 26](https://cloud.githubusercontent.com/assets/3290856/17105537/b0f941d4-5255-11e6-8d03-c00fda8a562e.png)

I'm not sure what's causing this or how to fix it.

**Comment by briandealwis** [comment]
We're not signing our plugins.  Retitled.  @elharo found a nice link describing the process:

http://www.codetrails.com/blog/sign-your-eclipse-project

**Comment by elharo** [comment]
https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/89
