### ISSUE TITLE
Convert GoogleLoginService as an OSGi service

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-eclipse-tools#446]
Could be either OSGi-level or workbench-level. Perhaps starting at the OSGi level.

Note: UIElement#getServiceLocator() can be used to update UI.

**Comment by elharo** [comment]
Is this related to #395 ?

**Comment by chanseokoh** [comment]
From what I've learned (could be wrong), this is related to #395 but seems like a different matter.

**Comment by chanseokoh** [comment]
Closed by #486.
