### ISSUE TITLE
Oauth scopes documentation

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#461]
1. Make sure the design doc clearly lists the oAuth scopes we request and why. (or perhaps a separate doc?)
2. Link from GoogleLoginService.java to the relevant public documentation on the scopes we request.

**Comment by chanseokoh** [comment]
- Documented in the design doc: https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/wiki/Cloud-Tools-for-Eclipse-Technical-Design#oauth-20-scopes-requested

- [`GoogleLoginService` has a link to it.](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginService.java#L47)

Closing.

**Comment by patflynn** [comment]
Hey guys,

I mentioned this in a previous PR but you need more scopes than that.

For AE Flex deployment you'll need:
https://www.googleapis.com/auth/appengine.admin

**Comment by chanseokoh** [comment]
Don't worry. We will add scopes as we find we need to.

In fact, I think many of the scopes have been consolidated and they made `https://www.googleapis.com/auth/cloud-platform` to cover most of the things: https://docs.google.com/document/d/1SjocNWCMBgIv0DPRe5dbkxkclQVmxkOPjf1PPkXUHuE/edit#

[Here](https://developers.google.com/identity/protocols/googlescopes#appenginev1), App Engine API  lists only `https://www.googleapis.com/auth/cloud-platform` (which enables many other APIs too). Interestingly, there is no `https://www.googleapis.com/auth/appengine.admin`. Perhaps Flex is very new, so we may need the scope later. We will see. It'll be trivial to notice if Flex deployment is working or not when we get to that point.

**Comment by patflynn** [comment]
Yeah that was always the plan, but we tested this a few months back and
that scope was still required.  But it looks like there's been a recent
change (perhaps related to why the apiary logs don't get 'deploys'
anymore), as I just tested flex deployment out on intellij without the
scope and it does appear to work.

carry on.
