### ISSUE TITLE
JVM crash when debugging on local dev_appserver 

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/gcloud-eclipse-tools#473]
Running the `dev_appserver` under the debugger leads to a JVM crash on the first access to the dev server.  Seen with Google Cloud SDK 115, 117 and 119, and JDK 1.8.0_92 and _102. This was working without issue.  I can reproduce this outside of the Cloud Tools for Eclipse.

## Steps to repeat
  1. Create new _Google App Engine Standard Java Project_
  2. _Debug &rarr; Debug As Server_ and set up an App Engine local server and launch.  The console should look something like:
```
INFO     2016-07-28 01:33:21,354 devappserver2.py:769] Skipping SDK update check.
INFO     2016-07-28 01:33:21,416 api_server.py:205] Starting API server at: http://localhost:54217
INFO     2016-07-28 01:33:21,421 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-07-28 01:33:21,424 admin_server.py:116] Starting admin server at: http://localhost:8000
Jul 28, 2016 1:33:22 AM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
INFO: Overwriting system property key 'java.util.logging.config.file', value '/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/config/sdk/logging.properties' with value 'WEB-INF/logging.properties' from '/Users/bsd/Manumitting/Projects/GooglePluginEclipse/runtime-gcloud-CLEAR/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/bar/WEB-INF/appengine-web.xml'
Jul 28, 2016 1:33:22 AM com.google.appengine.tools.development.AbstractContainerService configure
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
Jul 28, 2016 1:33:23 AM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
Jul 28, 2016 1:33:23 AM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
Jul 28, 2016 1:33:23 AM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@localhost:54220
Jul 28, 2016 1:33:23 AM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:54220/
Jul 28, 2016 1:33:23 AM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:54220/_ah/admin
Jul 28, 2016 1:33:23 AM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
INFO: Dev App Server is now running
Jul 28, 2016 1:33:24 AM com.google.appengine.tools.development.LocalResourceFileServlet doGet
WARNING: No file found for: /_ah/warmup
INFO     2016-07-28 01:33:24,393 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 404 83
```
Notice the lines talking about `http://localhost:54220/` — this is not expected.

  3. Attempt to retrieve `http://localhost:8080/hello`.  See a JVM crash:
```
INFO     2016-07-28 01:50:53,843 module.py:788] default: "GET / HTTP/1.1" 403 83
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
ERROR    2016-07-28 01:50:54,977 http_runtime.py:396] bad runtime process port ['']
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
ERROR    2016-07-28 01:50:54,980 http_proxy.py:116] bad runtime process port ['']
INFO     2016-07-28 01:50:55,082 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 261
```

For some reason the `dev_appserver` is launching a second JVM with the same `-Xrunjdwp` flags.  The JVM crash is occurring as we launch the server with `—jvm_flag=-Xrunjdwp:transport=dt_socket,server=n,suspend=y,quiet=y,address=8009` which causes the JVM to connect to our debugger waiting on port 8009.  At this point our debugger is not listening, and so the JVM crashes (the `AGENT_ERROR_TRANSPORT_INIT` error above).

## Reproducing with just Maven and Google Cloud SDK

This can be reproduced outside of the Cloud Tools for Eclipse:
  1. Start a remote debugging session using 'socket listener' mode on port 8009.
     - In Eclipse: _Run > Debug Configurations…_ and create a _Remote Java Application_ configuration in listener mode on port 8009.)
  2. Create new Maven archetype project:
```
$ mvn archetype:generate \
      -Dfilter=com.google.appengine.archetypes:appengine-skeleton-archetype \
      -DgroupId=test -DartifactId=skeleton -Dversion=0.1.0-SNAPSHOT \
      -Dappengine-version=1.9.38 -Dgcloud-version=119.0 
$ cd skeleton
$ mvn package
$ ${GOOGLE_CLOUD_SDK_HOME}/bin/dev_appserver.py \
      $PWD/target/skeleton-0.1.0-SNAPSHOT \
      --jvm_flag=-Dappengine.user.timezone=UTC \
      --jvm_flag=-Xdebug \
      --jvm_flag=-Xrunjdwp:transport=dt_socket,server=n,suspend=y,quiet=y,address=8009
```
and then fetch `http://localhost:8080` from elsewhere.

If you run `execsnoop` you'll see that a second JVM is executed with the same JVM flags, including the `-Xrunjdwp` argument

**Comment by briandealwis** [comment]
I discovered that `dev_appserver` supports `--dev_appserver_log_level debug`  to show much more information, and then the admin interface also shows that there are two instances of the _default_ module started.  If I run `dev_appserver` with `--max_module_instances 1`, then all seems well.

**Comment by chanseokoh** [comment]
Do you think the IntelliJ plugin will suffer from the same problem?

**Comment by elharo** [comment]
Good fix. That said, JVMs shouldn't crash no matter what we do. Do you have a stack dump I can pass along to our internal JVM folks?

**Comment by briandealwis** [comment]
I've attached the log here.  It's not a normal crash as the JVM can't connect to the JVMTI agent that was specified on the command-line (since we're not listening for connections).  It would be nice if we could somehow configure our Connector to continue listening, but that doesn't seem to be supported.


[jvmti-crash-log.txt](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/files/388717/jvmti-crash-log.txt)

**Comment by briandealwis** [comment]
> Do you think the IntelliJ plugin will suffer from the same problem?

Possibly, depending on how the IntelliJ tooling connects to the JVM.  I changed our connection style to be socket-listen (`server=n`: the debugger waits for a connection from the JVM) as it rid us of timing problems.  With socket-connect, the JVM hangs waiting for a connection from the debugger, and so the `dev_appserver`'s proxy may never direct requests to the second instance.  But this is entirely speculation.
