### ISSUE TITLE
Use ide-login library

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-eclipse-tools#480]
https://github.com/GoogleCloudPlatform/ide-login

The library basically has one core class that is very lightweight, so I anticipate this will be somewhat like a refactoring task applying a new design pattern.

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/ide-login/issues/2

Should we publish the library to Maven Central and who can do that? (The library is already OGSi-fied.)

**Comment by chanseokoh** [comment]
I'm working on this.

@briandealwis, is it okay to do below (refreshing a command UI) in a non-UI context?

```java
    ICommandService commandService =
        (ICommandService) PlatformUI.getWorkbench().getService(ICommandService.class);
    commandService.refreshElements(
        "com.google.cloud.tools.eclipse.appengine.login.commands.loginCommand", null);
```

**Comment by briandealwis** [comment]
No you can't do it off-thread.  Wrap it in a `Display#asyncExec()`; you can get the display from the workbench.
