### ISSUE TITLE
Cannot deploy

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-eclipse-tools#482]
I'm on the master branch. Not sure if this is happens on my machine only.

Steps to reproduce:

1. Create a new project (either Maven-based or plain)
1. Do deploy
   * Nothing happens

I did some investigation: `null` is returned [here](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployCommandHandler.java#L51). Inside `getProject()`, it seems like `structuredSelection.getFirstElement()` doesn't return an instance of `IProject`.

**Comment by akerekes** [comment]
Fixed by #485
