### ISSUE TITLE
Login G icon conflicts with resize area on Mac OS X

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#518]
Very hard to hit with cursor; probably move it up and to the left 16 pixels or so in each dimension

**Comment by briandealwis** [comment]
When I install the fish food releases, it shows up on the left.  Unfortunately there's not much that can be done as there are no fixed anchors to target.  I tried `toolbar:org.eclipse.ui.trim.status?before=org.eclipse.ui.StatusLine`, but it's not shown — the status line is installed by `WorkbenchWindow` seemingly after the trim contributions are processed.  Plain `toolbar:org.eclipse.ui.trim.status` appears no different from the [current `toolbar:org.eclipse.ui.trim.status?after=additions`](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.login/plugin.xml#L35).

If it does show up on the right-hand side, the user can drag it over to the left.  I'm going to close this as _wontfix_ for the moment, and lets see what we can do with the multi-account work.

**Comment by chanseokoh** [comment]
Here's what I know (at least what happens on my machine):

If the IDE launches for the first time for a new workspace (which will show the welcome page), the button is on the left. This is the case for unit/integration testing.

However, if the IDE opens the workspace second time (no welcome page), the button is on the right.

**Comment by briandealwis** [comment]
Oh I see that; I was clearing my workspace.

Unfortunately this is as good as it gets for the status bar.  Eclipse doesn't provide any anchor points to target, and although I could maybe get something in for 4.6.1, we can't do anything for 4.5.  And contributions referencing missing anchor points are dropped.
