### ISSUE TITLE
Failure (see console) does not send output to console

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#519]
On login with failure:

![failure](https://cloud.githubusercontent.com/assets/1005544/17527322/df7a29a8-5e38-11e6-84f6-0366fac88766.png)

Note that this bug is not the failure itself but that there is no message in the console

**Comment by elharo** [comment]
In fact, I think this dialog should probably 

1. show the problem in its own text.
2. Have a different title than "TESTING AUTH"

i.e. not rely in the console at all.

**Comment by elharo** [comment]
It is likely going to System.out instead.

**Comment by chanseokoh** [comment]
Invalidated by #530. If you actually see a login failure, please re-open this or file a new bug.
