### ISSUE TITLE
Do we need to put jars in WEB-INF/lib?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#550]
Per https://cloud.google.com/appengine/docs/java/runtime

App Engine knows to use the Java runtime environment for your application when you use the AppCfg tool from the Java SDK to upload the app.

The App Engine API for Java is represented by the appengine-api-*.jar included with the SDK (where * represents the version of the API and the SDK). You select the version of the API your application uses by including this JAR in the application's WEB-INF/lib/ directory. If a new version of the Java runtime environment is released that introduces changes that are not compatible with existing apps, that environment will have a new version number. Your application will continue to use the previous version until you replace the JAR with the new version (from a newer SDK) and re-upload the app.

So:

1. Do we need to put the appengine-api-*.jar in WEB-INF/lib with the new project wizard or does gcloud do something different?
2. Do we need to make sure we rename this jar to include the version number?

**Comment by patflynn** [comment]
On Thu, Aug 11, 2016 at 12:20 PM, Elliotte Rusty Harold <
notifications@github.com> wrote:

> Per https://cloud.google.com/appengine/docs/java/runtime
>
> App Engine knows to use the Java runtime environment for your application
> when you use the AppCfg tool from the Java SDK to upload the app.
>
> The App Engine API for Java is represented by the appengine-api-*.jar
> included with the SDK (where * represents the version of the API and the
> SDK). You select the version of the API your application uses by including
> this JAR in the application's WEB-INF/lib/ directory. If a new version of
> the Java runtime environment is released that introduces changes that are
> not compatible with existing apps, that environment will have a new version
> number. Your application will continue to use the previous version until
> you replace the JAR with the new version (from a newer SDK) and re-upload
> the app.
>
> So:
>
>    1. Do we need to put the appengine-api-*.jar in WEB-INF/lib with the
>    enw project wizard or does gcloud do something different?
>
> I think you need it for the dev appserver. Staging strips out the library
since it's provided at runtime on app-engine.

**Comment by briandealwis** [comment]
This is already handled by the WTP publish step, which runs as part of the Run and Debug launches.
```
$ find .metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp -type f
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/index.html
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/META-INF/MANIFEST.MF
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/WEB-INF/appengine-web.xml
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/WEB-INF/classes/HelloAppEngine.class
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/WEB-INF/lib/appengine-api-labs.jar
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/WEB-INF/lib/appengine-api.jar
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/WEB-INF/lib/appengine-jsr107cache-0.0.0.jar
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/WEB-INF/lib/jsr107cache-1.1.jar
.metadata/.plugins/org.eclipse.wst.server.core/tmp0/testapp/WEB-INF/web.xml
```

**Comment by briandealwis** [comment]
(`appengine-api-stubs.jar` isn't present as I wasn't running with #547)

**Comment by ludoch** [comment]
api lab should not be there by default, as it is a user decision to play
with experimental lab apis (not recommended as not stable, only for gurus
wanting to try potential new stuff).
*jsr107*: same: only if it make sense for the developer. Remove it for
default projects.

the api jar is mandatory when you use GAE apis. If you don't you do not
need it. It is used local by the devappserver, for local runs and stripped
out in the deploy staging phase, as the server side will replace the one
you provide (potentially an old version) with the latest version in
standard.

**Comment by ludoch** [comment]
appengine-api-stubs is not for users, but local emulation of APIs in the
local java devserver.

**Comment by elharo** [comment]
Do we need to update the "Selecting Java Runtime" section of  https://cloud.google.com/appengine/docs/java/runtime? It specifically says that " You select the version of the API your application uses by including this JAR in the application's WEB-INF/lib/ directory." Is this no longer true?
