### ISSUE TITLE
Google preferences show up on non-Google projects

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#561]
e.g. here on a regular Java project with non App Engine pieces:

![image](https://cloud.githubusercontent.com/assets/1005544/17673057/64ffa040-62ed-11e6-8782-aa35b84becc3.png)

**Comment by elharo** [comment]
I suspect plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/plugin.xml needs an additional enabledWhen on

 <extension point="org.eclipse.ui.propertyPages">
 +    <page
 +        id="com.google.cloud.tools.eclipse"
 +        name="Google"
 +        class="com.google.cloud.tools.eclipse.properties.GooglePropertyPage">
 +    </page>
 +  </extension>

to check that the project has the app engine facet. 

May also need to check that the selection is the project and not, for example, a single file.

**Comment by patflynn** [comment]
I think this might be OK.  There are aspects of Google integration that
could apply to non app engine projects.

**Comment by elharo** [comment]
For the moment, there aren't though.
