### ISSUE TITLE
Wait until background jobs are finished before proceeding with SWTBot test

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#583]
There exists a utility method (waitForIdle?) to check that there are no jobs left. This is done now in tearDown method of AbstractProjectTest. Do also in SwtBotAppEngineActions before returning from each createXXX method

We hope this reduces test flakiness.

**Comment by chanseokoh** [comment]
#593 didn't automatically close this.
