### ISSUE TITLE
Google Cloud SDK: Error starting server for missing bundledpython

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/gcloud-eclipse-tools#589]
Hello,
I just installed the tool into my Eclipse Neon.
```
Eclipse Java EE IDE for Web Developers.

Version: Neon Release (4.6.0)
Build id: 20160613-1800
```
![image](https://cloud.githubusercontent.com/assets/12278553/17810324/c6307ea2-661c-11e6-901b-10bd460e563c.png)

I configured the Facets for the project
![image](https://cloud.githubusercontent.com/assets/12278553/17810289/8926c7a0-661c-11e6-868d-e8cd3b2b6416.png)

configured the runtime
![image](https://cloud.githubusercontent.com/assets/12278553/17810296/8f20644a-661c-11e6-9327-677d317fc453.png)

created a new server
![image](https://cloud.githubusercontent.com/assets/12278553/17810303/9ac2af06-661c-11e6-98f0-2cb1eaa17196.png)

Launching the server I get the following error:

> Google Cloud SDK: Error starting server: com.google.cloud.tools.appengine.cloudsdk.internal.process.ProcessRunnerException: java.io.IOException: Cannot run program "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe": CreateProcess error=2, File not found
> An exception stack trace is not available.
> 
> Google Cloud SDK: Error terminating server: java.net.ConnectException: Connection refused: connect
> 
> Server (server name) failed to start.

Here is my GCloud installation
```
+--------------------------------------------------------------------------------------------+
|                                         Components                                         |
+---------------+-------------------------------------+--------------------------+-----------+
|     Status    |                 Name                |            ID            |    Size   |
+---------------+-------------------------------------+--------------------------+-----------+
| Not Installed | App Engine Go Extensions            | app-engine-go            |  46.8 MiB |
| Not Installed | Cloud Datastore Emulator            | cloud-datastore-emulator |  16.1 MiB |
| Not Installed | Cloud Pub/Sub Emulator              | pubsub-emulator          |  16.3 MiB |
| Not Installed | gcloud app PHP Extensions (Windows) | app-engine-php-windows   |  19.1 MiB |
| Not Installed | kubectl                             | kubectl                  |  11.3 MiB |
| Installed     | BigQuery Command Line Tool          | bq                       |   < 1 MiB |
| Installed     | Cloud Datastore Emulator (Legacy)   | gcd-emulator             |  38.1 MiB |
| Installed     | Cloud SDK Core Libraries            | core                     |   4.0 MiB |
| Installed     | Cloud Storage Command Line Tool     | gsutil                   |   2.7 MiB |
| Installed     | Default set of gcloud commands      | gcloud                   |           |
| Installed     | gcloud Alpha Commands               | alpha                    |   < 1 MiB |
| Installed     | gcloud Beta Commands                | beta                     |   < 1 MiB |
| Installed     | gcloud app Java Extensions          | app-engine-java          | 131.0 MiB |
| Installed     | gcloud app Python Extensions        | app-engine-python        |   7.2 MiB |
+---------------+-------------------------------------+--------------------------+-----------+
```

Here is my GCloud installation folder
![image](https://cloud.githubusercontent.com/assets/12278553/17810255/53fc6f80-661c-11e6-9d7c-b093a080af7c.png)
As you can see there is no `bundledpython` folder inside the `platform` folder.

GCloud was already installed before, but I updated all the components.

Is there a way to force GCloud download the bundledpython?

Thanks
Regards

**Comment by chanseokoh** [comment]
Hi @NicolaSpreafico,

Thank you very much for filing an issue.

We have been notified of the same issue by another user. The workaround for now is to reinstall the gcloud using the (preferably latest) installer. You would see an option, which is selected by default, to include the bundled python during installation.

Thanks,
Chanseok

**Comment by NicolaSpreafico** [comment]
Hi @chanseokoh ,

Sorry to open a duplicated issues, I did a search before opening the issue and I did not found any related issues.

Thank you for the provided workaround.

Regards

**Comment by chanseokoh** [comment]
No problem. In fact, the previous issue report was an internal one we received yesterday, and the issue has never been opened on our GitHub repo. Thanks for opening the issue!

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/189

**Comment by elharo** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/189
