### ISSUE TITLE
How to rollback a failed (or aborted) deploy

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/gcloud-eclipse-tools#591]
Hello,
with the previous plugin it was possibile to rollback a previous deploy which has been aborted.

![image](https://cloud.githubusercontent.com/assets/12278553/17811965/58cdc532-6625-11e6-9e78-e681b70a59c8.png)

If you try to deploy again w/o rolling back the previous attempt, you get an error
```
ago 19, 2016 3:57:32 PM com.google.appengine.tools.admin.AbstractServerConnection send1
AVVERTENZA: Error posting to URL: https://appengine.google.com/api/appversion/create?module=default&app_id=********&version=**************&
409 Conflict
Another transaction by user ******** is already in progress for app: ********, version: ********. That user can undo the transaction with "appcfg rollback".
```

And to resolve the problem it is required to do a rollback
```
Reading application configuration data...
ago 19, 2016 3:58:44 PM com.google.apphosting.utils.config.IndexesXmlReader readConfigXml
INFORMAZIONI: Successfully processed 
.........\WEB-INF/datastore-indexes.xml


Beginning interaction for module default...
0% Rolling back the update.
Success.
Cleaning up temporary files for module default...
```

With the newer plugin there is only the DEPLOY option
![image](https://cloud.githubusercontent.com/assets/12278553/17812338/ee680e62-6626-11e6-865a-de3a23d94b11.png)

Is there a way to reach the same goal using the newer gcloud plugin?

Thanks
Regards

**Comment by briandealwis** [comment]
> Is there a way to reach the same goal using the newer gcloud plugin? 

Unfortunately not yet.  There's some discussion around this functionality, but nothing implemented yet.

For now you'll need to use the command-line:
```
$GCLOUDSDK/platform/google_appengine/appcfg.py rollback  -A _appId_ _path_
```
`-A _appId_` is the Project ID that you attempted to deploy to, and may not be necessary if your `appengine-web.xml` has the Application ID.
_path_ needs to point to the directory containing your `WEB-INF`

**Comment by NicolaSpreafico** [comment]
Hi @briandealwis ,
thank you for the snippet.

For the (rare) cases I will need to do a rollback I will try the command you suggested.

**Comment by patflynn** [comment]
I think 'rollback' as a concept is deprecated in the new Cloud SDK based
deployment flow. The new deployment flow doesn't have the transactional
properties that requires any cleanup after a failed deployment.

**Comment by elharo** [comment]
I'm trying to get a definitive answer on this. I'm hoping that @patflynn is correct and we simply don't need this anymore.

**Comment by elharo** [comment]
I've confirmed that this functionality is no longer necessary. It used to be, but in 2016 the nature of deploys on the server side has changed such that there should be no need to explicitly run appcfg rollback or equivalent under any circumstances.

**Comment by NicolaSpreafico** [comment]
Hi @elharo,
can you also confirm that this is true if the deploy is made through GCloud SDK?

Because to make the screenshots I deployed (and aborted) using the old Eclipse Plugin and the error is still there.

Thanks

**Comment by elharo** [comment]
The old plugin uses appcfg. gcloud doesn't require this.
