### ISSUE TITLE
Re-implement App Engine deploy

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#66]
The code moved from the legacy plugin depends on an old version of gcloud to do the deploy, but that capability has been removed. The current implementation needs to be modified to use either the gcloud-maven-plugin or the app-maven-plugin for deployment.

**Comment by akerekes** [comment]
In plugin.xml when testing whether the action to deploy is enabled @briandealwis has the following proposal:

```
<extension
         point="org.eclipse.ui.handlers">
      <handler
            class="com.google.cloud.tools.eclipse.appengine.localserver.deploy.CloudSdkDeployProjectHandler"
            commandId="com.google.cloud.tools.eclipse.deployCommand">
         <enabledWhen>
```

> You could test for adapt to IProject to short-circuit the property tester.

**Comment by elharo** [comment]
obsolete; we're not bringing this code foward
