### ISSUE TITLE
Make icon square

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#7]
Right now the App Engine icon is 18x16. and gets squished into a square. We need to get a 16x16 square icon.

**Comment by briandealwis** [comment]
There's a 16x16 icon in [GPE](https://github.com/GoogleCloudPlatform/google-plugin-for-eclipse/blob/master/plugins/com.google.appengine.eclipse.core/icons/ae-deploy_16x16.png)
