### ISSUE TITLE
Use dev_appserver.py output to collect available command line flags

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#70]
Once dev_appserver.py supports formatting its output as json, we should use that to gather the available flags that can be passed to it in the command line, affects `com.google.cloud.tools.eclipse.appengine.localserver.server.CloudSdkServerFlags.getFlags()`

**Comment by akerekes** [comment]
related to #74

**Comment by elharo** [comment]
custom runtime is gone
