### ISSUE TITLE
Filter gcloud output when checking installed components

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#73]
When we check whether the required components are installed for gcloud the command returns all components with their corresponding status. We should use the new filter option to be released soon (soon wrt 4/15/2016) to reduce the output from gcloud to the necessary components. Most likely the following command will give the desired result:
`gcloud components list --filter=id:app-engine-java --format='value(state.name)'`

**Comment by briandealwis** [comment]
Is there a way to have gcloud stop checking for updates?  The update messages make parsing difficult…

```
$ gcloud components list --format=json

Your current Cloud SDK version is: 103.0.0
The latest available version is: 105.0.0

[
  {
    "current_version_string": "2016.03.28",
    "id": "core",
    "is_configuration": false,
    […etc…]
  }
]
To install or remove components at your current SDK version [103.0.0], run:
  $ gcloud components install COMPONENT_ID
  $ gcloud components remove COMPONENT_ID

To update your SDK installation to the latest version [105.0.0], run:
  $ gcloud components update

```

**Comment by akerekes** [comment]
The version/update related output is in fact written to stderr, so stdout contains only the json formatted result (e.g. ` gcloud components list --format=json 2>/dev/null`)

**Comment by elharo** [comment]
custom runtime is gone
