### ISSUE TITLE
Implement integration tests with Cloud SDK

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#76]
We should implement integration tests to ensure that the commands we construct are accepted by gcloud/dev_appserver.py (or any other utility we depend on).
These integration tests should run only if explicitly requested by the user when running the mvn build so as no to require each build environment to have Cloud SDK installed.
Possible solution is to use @Category from JUnit, Tycho 0.25 introduced support for it.

**Comment by elharo** [comment]
custom runtime is gone
this is now the domain of app-tools-lib-for-java
