### ISSUE TITLE
Verify whether debug and admin port is available when running launching dev app server in debug mode

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#77]
The code in `com.google.cloud.tools.eclipse.appengine.localserver.server.CloudSdkServerBehaviour.canStart(String)` checks only for the API port being available, but the server requires an admin port and in debug mode a debug port to be available. This method is called when the UI refreshes and deiced whether to enable/disable the launch buttons in the `Servers` view.

Although it'd be more explicit for the user if the ports are not available, then this could be displayed to the user either via a tooltip on the disabled buttons or an error dialog when the user clicks on the buttons.

**Comment by elharo** [comment]
obsolete, we're not bringing this code forward
