### ISSUE TITLE
Allow native WTP projects to be run/debug on dev app server

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#78]
We currently support only Maven projects that has the gcloud-maven-plugin configured to be run/debugged on the local dev app server, see: `com.google.cloud.tools.eclipse.appengine.localserver.facet.CloudSdkFacetInstallDelegate#execute()`

We should allow for non-Maven WTP projects as well.

**Comment by rdayal** [comment]
Can you all clarify this task?

**Comment by rdayal** [comment]
I don't know how important this is. The main case we are supporting is for Maven projects, and we're not really recommending the native project path. If I'm misunderstanding something, let me know.

**Comment by briandealwis** [comment]
This requirement was moved with the removal of the `com.google.cloud.tools.eclipse.facet` facet for #219
