### ISSUE TITLE
Change dev app server extension point ids, names, descriptions

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#79]
The current values in `/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml` are either include implementation details (referring to Cloud SDK) or do not contain enough details and therefore ambiguous (e.g. `com.google.cloud.tools.eclipse.facet`).
We should change these values and through naming we should convey that these extension points are for App Engine/App Engine Standard related features in order to allow for App Enginge Flex, GCE, GKE related extension points that follow a standard naming convention. Also, if possible, we could shorten the current names from com.google.cloud.tools.eclipse.* to com.google.<env_type>.*, where env_type could be ae1/ae.std, ae.flex, gce, gke for instance.

**Comment by elharo** [comment]
obsolete
