### ISSUE TITLE
Refactor com.google.cloud.tools.eclipse.appengine.localserver plugin to separate concerns

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#80]
The `com.google.cloud.tools.eclipse.appengine.localserver` plugin currently contains all code required to run web app on a local dev app server, but the UI and non-UI code should be separated into 2 plugins.

Furthermore the code that interacts with Cloud SDK/gcloud/dev_appserver.py should also be moved into its own plugin as other features will also depend on it (like e.g. support for App Engine Flex environment)

Also there are several utility classes (mostly the `com.google.cloud.tools.eclipse.util` package) that are currently used only in this plugin but can be useful in plugins implemented in the future, so these should also be moved into a separate plugin.

**Comment by briandealwis** [comment]
Closing this — obsolete with changes to the server definitions.
