### ISSUE TITLE
Replace CloudSdkProjectPropertyTester with expression

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#81]
@briandealwis 's suggestion:
rather than define our own property tester in `com.google.cloud.tools.eclipse.appengine.localserver.deploy.CloudSdkProjectPropertyTester`, it's probably better from an extensibility perspective to provide an expression definition (org.eclipse.core.expressions.definition) so we can vary the implementation

WTP provides a [facet property tester](https://eclipse.org/articles/Article-BuildingProjectFacets/tutorial.html#property.tester)

**Comment by elharo** [comment]
custom runtime is gone
