### ISSUE TITLE
Test and possibly simplify code in CloudSdkServerLaunchTab

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#83]
Using a TraverseListener in `com.google.cloud.tools.eclipse.appengine.localserver.ui.CloudSdkServerLaunchTab.createControl(Composite)` might be overkill, we should test whether using `SWT.DefaultSelection` or `SelectionListener#widgetDefaultSelected()` on Text fields is sufficient.

**Comment by elharo** [comment]
custom runtime is gone
