### ISSUE TITLE
com.google.cloud.tools.eclipse.appengine.localserver.server.CloudSdkServerStartupChecker should use Job instead of Thread

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#86]
In `com.google.cloud.tools.eclipse.appengine.localserver.server.CloudSdkServerStartupChecker` a thread is used to ping the server to see if it has started yet. Instead of a thread, we should use a Job that can reschedule itself if necessary to wait longer for the server startup.

**Comment by elharo** [comment]
custom runtime is gone
