### ISSUE TITLE
Implement ProcessUtilitiesTest methods to support Windows

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/gcloud-eclipse-tools#87]
`com.google.cloud.tools.eclipse.appengine.localserver.util.ProcessUtilitiesTest.testlaunchProcessAndWaitFor_additionalPathAdded()` works on Linux/Mac, needs to be modified to make it compatible with Windows.

**Comment by elharo** [comment]
obsolete. This is now part of app-tools-lib-for-java
