### ISSUE TITLE
Fix license text

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#88]
On install the license text is "license"
![screen shot 2016-04-21 at 3 03 41 pm](https://cloud.githubusercontent.com/assets/1005544/14721033/3dd76a78-07d2-11e6-8efb-e35e3c7e1431.png)

**Comment by elharo** [comment]
Possibly related, wizard.description is also not getting picked up:

![screen shot 2016-04-21 at 3 07 00 pm](https://cloud.githubusercontent.com/assets/1005544/14721126/c0d9a814-07d2-11e6-92ef-03c5436b1275.png)

**Comment by briandealwis** [comment]
%wizard.description isn't related: `.newproject` is missing a `Bundle-Localization: plugin` line to direct message translations for MANIFEST.MF and plugin.xml to the `plugin.properties`.
