### ISSUE TITLE
Autolocate gcloud SDK if present

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#9]
Rather than making user select it.

**Comment by rdayal** [comment]
I think you can rely on the common library that Patrick and co are working on to help you with this.

**Comment by meltsufin** [comment]
Yes, we have this [PathResolver](https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/blob/master/src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/PathResolver).

**Comment by elharo** [comment]
In other words, fill out findCloudSdk in CreateAppEngineStandardWtpProject. 

I'm not sure if this is necessary for the maven project or not.
